spring.application.name=sensor

# profile(local, dev, prod)
spring.profiles.active=local

# context path
server.servlet.context-path=/sensor
server.port=8080

# thymeleaf path
spring.thymeleaf.prefix=classpath:thymeleaf/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# server restart
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# jasypt
jasypt.encryptor.bean=jasyptStringEncryptor