# mongodb
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=sensordb
spring.data.mongodb.username=ENC(Qtr36ROwlvxc3b/aVsWQYp4DawX3up8jYhHJK1aWfVAB/6gBXvzWRuAP/WtVEt21)
spring.data.mongodb.password=ENC(3ZGG/pgX+Hr2gRo1ZQ8EpewKFjEh3nh8+3r3FUB9auxrWOpsYUkDkCTWuhoMHtQV)
spring.data.mongodb.authentication-database=ENC(dkrc8hPlSPZrHRmaRVjiBWGUnD4pQc0xL2fD3hINRPIRvml4zC1IEc/lUwKrEbOL)

# logback
log.filePath=C:/logs/sensor

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG